"""create initial tables for reservoirs, wells, production, pvt, and simulations

Revision ID: 20240710_0001
Revises:
Create Date: 2024-07-10 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "20240710_0001"
down_revision = None  # This is the first migration
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reservoirs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("formation_type", sa.String(length=50), nullable=True),
        sa.Column("initial_pressure", sa.Float(), nullable=True),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("porosity", sa.Float(), nullable=True),
        sa.Column("permeability", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_reservoirs_id"), "reservoirs", ["id"], unique=False)

    op.create_table(
        "wells",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("well_type", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("depth", sa.Float(), nullable=True),
        sa.Column("reservoir_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["reservoir_id"],
            ["reservoirs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wells_id"), "wells", ["id"], unique=False)

    op.create_table(
        "simulations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reservoir_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.Column("parameters", sa.Text(), nullable=True),
        sa.Column("results_path", sa.String(length=200), nullable=True),
        sa.Column(
            "run_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["reservoir_id"],
            ["reservoirs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_simulations_id"), "simulations", ["id"], unique=False)

    op.create_table(
        "production_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("well_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("oil_rate", sa.Float(), nullable=True),
        sa.Column("gas_rate", sa.Float(), nullable=True),
        sa.Column("water_rate", sa.Float(), nullable=True),
        sa.Column("bottomhole_pressure", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["well_id"],
            ["wells.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_production_data_id"), "production_data", ["id"], unique=False
    )

    op.create_table(
        "pvt_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("well_id", sa.Integer(), nullable=False),
        sa.Column("pressure", sa.Float(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("oil_fvf", sa.Float(), nullable=True),
        sa.Column("gas_fvf", sa.Float(), nullable=True),
        sa.Column("oil_viscosity", sa.Float(), nullable=True),
        sa.Column("gas_viscosity", sa.Float(), nullable=True),
        sa.Column("solution_gor", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["well_id"],
            ["wells.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pvt_data_id"), "pvt_data", ["id"], unique=False)

    # Added User table from 13c8cedc2a5f
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "username", sa.String(), nullable=False
        ),  # Adjusted String length later if needed by models
        sa.Column(
            "email", sa.String(), nullable=False
        ),  # Adjusted String length later if needed by models
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.Date(), nullable=True
        ),  # Model default handles non-null
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")

    op.drop_index(op.f("ix_pvt_data_id"), table_name="pvt_data")
    op.drop_table("pvt_data")
    op.drop_index(op.f("ix_production_data_id"), table_name="production_data")
    op.drop_table("production_data")
    op.drop_index(op.f("ix_simulations_id"), table_name="simulations")
    op.drop_table("simulations")
    op.drop_index(op.f("ix_wells_id"), table_name="wells")
    op.drop_table("wells")
    op.drop_index(op.f("ix_reservoirs_id"), table_name="reservoirs")
    op.drop_table("reservoirs")
    # ### end Alembic commands ###
