"""check_models_alignment_after_upgrade_and_fix

Revision ID: 401430a27bdb
Revises: 20240710_0001
Create Date: 2025-07-05 18:41:45.792839

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "401430a27bdb"
down_revision: Union[str, Sequence[str], None] = "20240710_0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reservoirs_id"), table_name="reservoirs")
    op.drop_table("reservoirs")
    op.drop_index(op.f("ix_pvt_data_id"), table_name="pvt_data")
    op.drop_table("pvt_data")
    op.drop_index(op.f("ix_simulations_id"), table_name="simulations")
    op.drop_table("simulations")
    op.create_unique_constraint("_well_date_uc", "production_data", ["well_id", "date"])
    op.drop_column("production_data", "created_at")
    op.drop_column("production_data", "bottomhole_pressure")
    op.add_column("wells", sa.Column("field", sa.String(), nullable=True))
    op.add_column("wells", sa.Column("latitude", sa.Float(), nullable=True))
    op.add_column("wells", sa.Column("longitude", sa.Float(), nullable=True))
    op.alter_column(
        "wells",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        type_=sa.Date(),
        existing_nullable=True,
    )
    op.create_index(op.f("ix_wells_name"), "wells", ["name"], unique=True)
    op.drop_constraint(None, "wells", type_="foreignkey")
    op.drop_column("wells", "depth")
    op.drop_column("wells", "well_type")
    op.drop_column("wells", "status")
    op.drop_column("wells", "reservoir_id")
    op.drop_column("wells", "updated_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wells",
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
    )
    op.add_column("wells", sa.Column("reservoir_id", sa.INTEGER(), nullable=False))
    op.add_column("wells", sa.Column("status", sa.VARCHAR(length=20), nullable=True))
    op.add_column("wells", sa.Column("well_type", sa.VARCHAR(length=20), nullable=True))
    op.add_column("wells", sa.Column("depth", sa.FLOAT(), nullable=True))
    op.create_foreign_key(None, "wells", "reservoirs", ["reservoir_id"], ["id"])
    op.drop_index(op.f("ix_wells_name"), table_name="wells")
    op.alter_column(
        "wells",
        "created_at",
        existing_type=sa.Date(),
        server_default=sa.text("(CURRENT_TIMESTAMP)"),
        type_=sa.DATETIME(),
        existing_nullable=True,
    )
    op.drop_column("wells", "longitude")
    op.drop_column("wells", "latitude")
    op.drop_column("wells", "field")
    op.add_column(
        "production_data", sa.Column("bottomhole_pressure", sa.FLOAT(), nullable=True)
    )
    op.add_column(
        "production_data",
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
    )
    op.drop_constraint("_well_date_uc", "production_data", type_="unique")
    op.create_table(
        "simulations",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("reservoir_id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=True),
        sa.Column("type", sa.VARCHAR(length=50), nullable=True),
        sa.Column("parameters", sa.TEXT(), nullable=True),
        sa.Column("results_path", sa.VARCHAR(length=200), nullable=True),
        sa.Column(
            "run_date",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("status", sa.VARCHAR(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["reservoir_id"],
            ["reservoirs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_simulations_id"), "simulations", ["id"], unique=False)
    op.create_table(
        "pvt_data",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("well_id", sa.INTEGER(), nullable=False),
        sa.Column("pressure", sa.FLOAT(), nullable=False),
        sa.Column("temperature", sa.FLOAT(), nullable=False),
        sa.Column("oil_fvf", sa.FLOAT(), nullable=True),
        sa.Column("gas_fvf", sa.FLOAT(), nullable=True),
        sa.Column("oil_viscosity", sa.FLOAT(), nullable=True),
        sa.Column("gas_viscosity", sa.FLOAT(), nullable=True),
        sa.Column("solution_gor", sa.FLOAT(), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["well_id"],
            ["wells.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pvt_data_id"), "pvt_data", ["id"], unique=False)
    op.create_table(
        "reservoirs",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("location", sa.VARCHAR(length=200), nullable=True),
        sa.Column("formation_type", sa.VARCHAR(length=50), nullable=True),
        sa.Column("initial_pressure", sa.FLOAT(), nullable=True),
        sa.Column("temperature", sa.FLOAT(), nullable=True),
        sa.Column("porosity", sa.FLOAT(), nullable=True),
        sa.Column("permeability", sa.FLOAT(), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_reservoirs_id"), "reservoirs", ["id"], unique=False)
    # ### end Alembic commands ###
