// This is a placeholder for the auto-generated API client.
// In a real scenario, this file would be generated by:
// npx openapi-typescript http://localhost:8000/openapi.json --output ./lib/apiClientGenerated.ts

export interface paths {
  "/api/v1/users/me": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": {
              email: string;
              username: string;
              is_active: boolean;
              is_superuser: boolean;
            };
          };
        };
      };
    };
  };
  "/api/v1/login/access-token": {
    post: {
      requestBody: {
        content: {
          "application/x-www-form-urlencoded": {
            grant_type?: string;
            username?: string;
            password?: string;
            scope?: string;
            client_id?: string;
            client_secret?: string;
          };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              access_token: string;
              token_type: string;
            };
          };
        };
        400: {
          content: {
            "application/json": {
              detail: string;
            };
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    UserRead: {
      email: string;
      username: string;
      is_active?: boolean;
      is_superuser?: boolean;
    };
    Token: {
      access_token: string;
      token_type?: string;
    };
    Body_login_for_access_token_api_v1_login_access_token_post: {
      grant_type?: string;
      username?: string;
      password?: string;
      scope?: string;
      client_id?: string;
      client_secret?: string;
    };
    HTTPValidationError: {
      detail?: Array<{
        loc: string[];
        msg: string;
        type: string;
      }>;
    };
  };
}

// Minimal fetcher type, actual generated client might have more complex options
export type Fetcher = (
  url: string,
  options?: RequestInit
) => Promise<any>;

// Example of how a client might be structured (highly simplified)
// The actual openapi-typescript output would be more comprehensive.
// This is just to have something to import.
export default function createClient<T extends Fetcher>(fetcher: T) {
  return {
    GET: async (url: keyof paths, params?: any) => {
      // Basic parameter handling (actual generator is more sophisticated)
      const path = params ? `${String(url)}?${new URLSearchParams(params)}` : String(url);
      return fetcher(path, { method: "GET" });
    },
    POST: async (url: keyof paths, body?: any, params?: any) => {
      // Basic parameter handling
      const path = params ? `${String(url)}?${new URLSearchParams(params)}` : String(url);
      return fetcher(path, {
        method: "POST",
        headers: { "Content-Type": "application/json" }, // Assuming JSON body
        body: JSON.stringify(body),
      });
    },
    // ... other HTTP methods
  };
}

// Placeholder for specific API functions if the generator creates them
// For example:
// export const getApiV1UsersMe = (fetcher: Fetcher) => {
//   return fetcher("/api/v1/users/me", { method: "GET" });
// }
//
// export const loginForAccessTokenApiV1LoginAccessTokenPost = (fetcher: Fetcher, body: components["schemas"]["Body_login_for_access_token_api_v1_login_access_token_post"]) => {
//   return fetcher("/api/v1/login/access-token", {
//     method: "POST",
//     headers: { "Content-Type": "application/x-www-form-urlencoded" }, // As per example
//     body: new URLSearchParams(Object.entries(body as Record<string, string>)).toString(),
//   });
// }
